-- Analyze how CHANGES and MUTATION relate to CMFCASE/CMFRECORD in original captured data

DECLARE @RunID UNIQUEIDENTIFIER;
SELECT TOP 1 @RunID = RunID
FROM dbo.MigrationScenarioRun
WHERE EndedAt IS NOT NULL
ORDER BY StartedAt DESC;

PRINT '=== Original Captured Data Analysis ===';
PRINT 'RunID: ' + CAST(@RunID AS NVARCHAR(50));
PRINT '';

-- Get the captured individual and case
PRINT '=== Captured Individual and Case ===';
SELECT 
    i.INDIVIDUALRECORDID,
    i.CASEID,
    i.FIRSTNAMES,
    i.SURNAME,
    p.CASESTATUS,
    c.ID AS CMFCaseID
FROM SC_PERSONREGISTRATION_INDIVIDUAL i
INNER JOIN SC_PERSONREGISTRATION_PROPERTIES p ON p.CASEID = i.CASEID
LEFT JOIN CMFCASE c ON c.ID = i.CASEID
WHERE i.INDIVIDUALRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
);

-- Get CHANGES records for this individual
PRINT '';
PRINT '=== CHANGES Records ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.CHANGERECORDID,
    ch.CASEID,
    ch.TOPICOFCHANGE,
    ch.MUTATIONRECORDID,
    ch.CHANGESTATUS,
    i.INDIVIDUALRECORDID,
    i.FIRSTNAMES,
    i.SURNAME
FROM CHANGES ch
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = ch.CHANGERECORDID
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'CHANGES'
)
ORDER BY ch.CHANGESRECORDID;

-- Get MUTATION records
PRINT '';
PRINT '=== MUTATION Records ===';
SELECT 
    m.MUTATIONRECORDID,
    m.CASEID,
    m.CHANGESTATUS,
    m.EXTERNALMUTATIONGUID
FROM MUTATION m
WHERE m.MUTATIONRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'MUTATION'
)
ORDER BY m.MUTATIONRECORDID;

-- Check CMFRECORD relationships
PRINT '';
PRINT '=== CMFRECORD Relationships ===';
SELECT 
    r.ID AS CMFRecordID,
    r.CASEID,
    r.RECORDTYPE,
    r.RECORDSTATUS,
    CASE 
        WHEN r.ID IN (SELECT CHANGERECORDID FROM CHANGES WHERE CHANGESRECORDID IN (
            SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow WHERE RunID = @RunID AND TableName = 'CHANGES'
        )) THEN 'CHANGES.CHANGERECORDID'
        WHEN r.ID IN (SELECT MUTATIONRECORDID FROM CHANGES WHERE CHANGESRECORDID IN (
            SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow WHERE RunID = @RunID AND TableName = 'CHANGES'
        )) THEN 'CHANGES.MUTATIONRECORDID'
        WHEN r.ID IN (SELECT CASEID FROM CHANGES WHERE CHANGESRECORDID IN (
            SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow WHERE RunID = @RunID AND TableName = 'CHANGES'
        )) THEN 'CHANGES.CASEID'
        ELSE 'Other'
    END AS UsedIn
FROM CMFRECORD r
WHERE r.CASEID IN (
    SELECT i.CASEID FROM SC_PERSONREGISTRATION_INDIVIDUAL i
    WHERE i.INDIVIDUALRECORDID IN (
        SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
        WHERE RunID = @RunID AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
    )
)
ORDER BY r.ID;

-- Check if CHANGES.CHANGERECORDID points to CMFRECORD or SC_PERSONREGISTRATION_INDIVIDUAL
PRINT '';
PRINT '=== CHANGES.CHANGERECORDID Analysis ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.CHANGERECORDID,
    ch.TOPICOFCHANGE,
    CASE 
        WHEN i.INDIVIDUALRECORDID IS NOT NULL THEN 'Points to SC_PERSONREGISTRATION_INDIVIDUAL'
        WHEN r.ID IS NOT NULL THEN 'Points to CMFRECORD'
        ELSE 'Points to nothing (broken)'
    END AS PointsTo,
    COALESCE(i.FIRSTNAMES + ' ' + i.SURNAME, 'CMFRECORD #' + CAST(r.ID AS NVARCHAR(20)), 'BROKEN') AS TargetInfo
FROM CHANGES ch
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = ch.CHANGERECORDID
LEFT JOIN CMFRECORD r ON r.ID = ch.CHANGERECORDID
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'CHANGES'
);

-- Check if CHANGES.MUTATIONRECORDID points to MUTATION or CMFRECORD
PRINT '';
PRINT '=== CHANGES.MUTATIONRECORDID Analysis ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.MUTATIONRECORDID,
    CASE 
        WHEN m.MUTATIONRECORDID IS NOT NULL THEN 'Points to MUTATION table'
        WHEN r.ID IS NOT NULL THEN 'Points to CMFRECORD'
        ELSE 'NULL or broken'
    END AS PointsTo
FROM CHANGES ch
LEFT JOIN MUTATION m ON m.MUTATIONRECORDID = ch.MUTATIONRECORDID
LEFT JOIN CMFRECORD r ON r.ID = ch.MUTATIONRECORDID
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'CHANGES'
);
