-- Analyze how CHANGES and MUTATION relate to CMFCASE/CMFRECORD

DECLARE @RunID UNIQUEIDENTIFIER;
SELECT TOP 1 @RunID = RunID
FROM dbo.MigrationScenarioRun
WHERE EndedAt IS NOT NULL
ORDER BY StartedAt DESC;

PRINT '=== Captured Individual and Case ===';
SELECT 
    i.INDIVIDUALRECORDID,
    i.CASEID,
    i.FIRSTNAMES,
    i.SURNAME
FROM SC_PERSONREGISTRATION_INDIVIDUAL i
WHERE i.INDIVIDUALRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
);

PRINT '';
PRINT '=== CHANGES Records ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.CHANGERECORDID,
    ch.CASEID,
    ch.TOPICOFCHANGE,
    ch.MUTATIONRECORDID
FROM CHANGES ch
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'CHANGES'
);

PRINT '';
PRINT '=== What does CHANGERECORDID point to? ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.CHANGERECORDID,
    ch.TOPICOFCHANGE,
    CASE 
        WHEN EXISTS (SELECT 1 FROM SC_PERSONREGISTRATION_INDIVIDUAL WHERE INDIVIDUALRECORDID = ch.CHANGERECORDID) THEN 'SC_PERSONREGISTRATION_INDIVIDUAL'
        WHEN EXISTS (SELECT 1 FROM CMFRECORD WHERE ID = ch.CHANGERECORDID) THEN 'CMFRECORD'
        ELSE 'UNKNOWN'
    END AS PointsToTable
FROM CHANGES ch
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @RunID AND TableName = 'CHANGES'
);

PRINT '';
PRINT '=== CMFRECORD for this case ===';
SELECT 
    r.ID,
    r.CASEID,
    r.RECORDTYPE
FROM CMFRECORD r
WHERE r.CASEID IN (
    SELECT i.CASEID FROM SC_PERSONREGISTRATION_INDIVIDUAL i
    WHERE i.INDIVIDUALRECORDID IN (
        SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
        WHERE RunID = @RunID AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
    )
);

PRINT '';
PRINT '=== Was CMFRECORD captured? ===';
SELECT 
    TableName,
    COUNT(*) AS CapturedRows
FROM dbo.MigrationScenarioRow
WHERE RunID = @RunID
  AND TableName IN ('CMFRECORD', 'CMFCASE', 'CMFEVENT', 'CMFTRANSITION')
GROUP BY TableName;
