-- Analyze the most recent replay of Don Juan
DECLARE @ReplayRunID UNIQUEIDENTIFIER;
SELECT TOP 1 @ReplayRunID = ReplayRunID
FROM dbo.MigrationScenarioReplayRun
ORDER BY ReplayRunID DESC;

PRINT 'ReplayRunID: ' + CAST(@ReplayRunID AS NVARCHAR(50));

-- Check the replayed individuals
PRINT '';
PRINT '=== Replayed Individuals ===';
SELECT 
    i.INDIVIDUALRECORDID,
    i.FIRSTNAMES,
    i.SURNAME,
    i.INDIVIDUALSTATUS,
    i.CASEID
FROM SC_PERSONREGISTRATION_INDIVIDUAL i
WHERE i.INDIVIDUALRECORDID IN (
    SELECT NewPkValue
    FROM dbo.MigrationScenarioReplayMap
    WHERE ReplayRunID = @ReplayRunID
      AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
)
ORDER BY i.INDIVIDUALRECORDID;

-- Check the replayed home addresses
PRINT '';
PRINT '=== Replayed Home Addresses ===';
SELECT 
    h.HOMEADDRESSRECORDID,
    h.CASEID,
    h.HOMEADDRESSCOUNTRY,
    h.HOMEADDRESSREGION,
    h.HOMEADDRESSSTREET,
    h.HOMEADDRESSHOUSENUMBER,
    h.HOMEADDRESSSTATUS
FROM SC_PERSONREGISTRATION_HOMEADDRESS h
WHERE h.HOMEADDRESSRECORDID IN (
    SELECT NewPkValue
    FROM dbo.MigrationScenarioReplayMap
    WHERE ReplayRunID = @ReplayRunID
      AND TableName = 'SC_PERSONREGISTRATION_HOMEADDRESS'
)
ORDER BY h.HOMEADDRESSRECORDID;

-- Check the replayed CHANGES
PRINT '';
PRINT '=== Replayed CHANGES ===';
SELECT 
    c.CHANGESRECORDID,
    c.CHANGERECORDID,
    c.TOPICOFCHANGE,
    c.UPDATETYPE,
    c.MUTATIONRECORDID,
    c.CASEID,
    CASE WHEN i.INDIVIDUALRECORDID IS NOT NULL THEN 'LINKED' ELSE 'BROKEN' END AS IndividualLink
FROM CHANGES c
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = c.CHANGERECORDID
WHERE c.CHANGESRECORDID IN (
    SELECT NewPkValue
    FROM dbo.MigrationScenarioReplayMap
    WHERE ReplayRunID = @ReplayRunID
      AND TableName = 'CHANGES'
)
  AND c.TOPICOFCHANGE = 'Individual'
ORDER BY c.CHANGESRECORDID;

-- Check the replayed MUTATION
PRINT '';
PRINT '=== Replayed MUTATION ===';
SELECT 
    m.MUTATIONRECORDID,
    m.CASEID,
    m.CHANGESTATUS,
    m.DATESTARTED,
    m.DATEFINALIZED
FROM MUTATION m
WHERE m.MUTATIONRECORDID IN (
    SELECT NewPkValue
    FROM dbo.MigrationScenarioReplayMap
    WHERE ReplayRunID = @ReplayRunID
      AND TableName = 'MUTATION'
)
ORDER BY m.MUTATIONRECORDID;

-- Check the original captured data
PRINT '';
PRINT '=== Original Captured Individual ===';
SELECT TOP 1
    JSON_VALUE(RowJson, '$.FIRSTNAMES') AS FIRSTNAMES,
    JSON_VALUE(RowJson, '$.SURNAME') AS SURNAME,
    JSON_VALUE(RowJson, '$.INDIVIDUALSTATUS') AS INDIVIDUALSTATUS
FROM dbo.MigrationScenarioRow
WHERE TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
ORDER BY CapturedAt DESC;

-- Check the original captured home address
PRINT '';
PRINT '=== Original Captured Home Address ===';
SELECT TOP 1
    JSON_VALUE(RowJson, '$.HOMEADDRESSCOUNTRY') AS HOMEADDRESSCOUNTRY,
    JSON_VALUE(RowJson, '$.HOMEADDRESSREGION') AS HOMEADDRESSREGION,
    JSON_VALUE(RowJson, '$.HOMEADDRESSSTREET') AS HOMEADDRESSSTREET,
    JSON_VALUE(RowJson, '$.HOMEADDRESSHOUSENUMBER') AS HOMEADDRESSHOUSENUMBER,
    JSON_VALUE(RowJson, '$.HOMEADDRESSSTATUS') AS HOMEADDRESSSTATUS
FROM dbo.MigrationScenarioRow
WHERE TableName = 'SC_PERSONREGISTRATION_HOMEADDRESS'
ORDER BY CapturedAt DESC;
