-- Check the actual replayed data
DECLARE @ReplayRunID UNIQUEIDENTIFIER;
SELECT TOP 1 @ReplayRunID = ReplayRunID
FROM dbo.MigrationScenarioReplayRun
ORDER BY ReplayRunID DESC;

-- Get the first replayed individual
DECLARE @FirstIndividualID BIGINT;
SELECT TOP 1 @FirstIndividualID = NewPkValue
FROM dbo.MigrationScenarioReplayMap
WHERE ReplayRunID = @ReplayRunID
  AND TableName = 'SC_PERSONREGISTRATION_INDIVIDUAL'
ORDER BY NewPkValue;

-- Get the case for this individual
DECLARE @CaseID BIGINT;
SELECT @CaseID = CASEID
FROM SC_PERSONREGISTRATION_INDIVIDUAL
WHERE INDIVIDUALRECORDID = @FirstIndividualID;

PRINT 'Checking Individual: ' + CAST(@FirstIndividualID AS NVARCHAR(20)) + ', Case: ' + CAST(@CaseID AS NVARCHAR(20));

-- Check the individual
SELECT 
    INDIVIDUALRECORDID,
    FIRSTNAMES,
    SURNAME,
    INDIVIDUALSTATUS,
    CASEID
FROM SC_PERSONREGISTRATION_INDIVIDUAL
WHERE INDIVIDUALRECORDID = @FirstIndividualID;

-- Check home address
PRINT '';
PRINT '=== Home Address ===';
SELECT 
    HOMEADDRESSRECORDID,
    CASEID,
    HOMEADDRESSCOUNTRY,
    HOMEADDRESSREGION,
    HOMEADDRESSSTREET,
    HOMEADDRESSHOUSENUMBER,
    HOMEADDRESSSTATUS,
    HOMEADDRESSSTARTINGDATE,
    DELETED,
    HOMEADDRESSEXPIRATIONDATE
FROM SC_PERSONREGISTRATION_HOMEADDRESS
WHERE CASEID = @CaseID;

-- Check CHANGES
PRINT '';
PRINT '=== CHANGES ===';
SELECT 
    CHANGESRECORDID,
    CHANGERECORDID,
    TOPICOFCHANGE,
    UPDATETYPE,
    MUTATIONRECORDID,
    CASEID,
    DELETED
FROM CHANGES
WHERE CASEID = @CaseID;

-- Check MUTATION
PRINT '';
PRINT '=== MUTATION ===';
SELECT 
    MUTATIONRECORDID,
    CASEID,
    CHANGESTATUS,
    DATESTARTED,
    DATEFINALIZED,
    DELETED
FROM MUTATION
WHERE CASEID = @CaseID;

-- Check if CHANGERECORDID points to the individual
PRINT '';
PRINT '=== CHANGERECORDID Link Check ===';
SELECT 
    c.CHANGESRECORDID,
    c.CHANGERECORDID,
    c.TOPICOFCHANGE,
    CASE 
        WHEN c.CHANGERECORDID = @FirstIndividualID THEN 'CORRECT'
        WHEN i.INDIVIDUALRECORDID IS NOT NULL THEN 'POINTS TO OTHER INDIVIDUAL'
        ELSE 'BROKEN - NO INDIVIDUAL FOUND'
    END AS LinkStatus
FROM CHANGES c
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = c.CHANGERECORDID
WHERE c.CASEID = @CaseID
  AND c.TOPICOFCHANGE = 'Individual';
