-- Understand what CHANGERECORDID should point to

DECLARE @OriginalRunID UNIQUEIDENTIFIER;
SELECT TOP 1 @OriginalRunID = RunID
FROM dbo.MigrationScenarioRun
WHERE EndedAt IS NOT NULL
ORDER BY StartedAt DESC;

PRINT '=== Original CHANGES and what CHANGERECORDID points to ===';
SELECT 
    ch.CHANGESRECORDID,
    ch.CHANGERECORDID,
    ch.TOPICOFCHANGE,
    CASE 
        WHEN i.INDIVIDUALRECORDID IS NOT NULL THEN 'SC_PERSONREGISTRATION_INDIVIDUAL (ID=' + CAST(i.INDIVIDUALRECORDID AS NVARCHAR(20)) + ')'
        WHEN r.ID IS NOT NULL THEN 'CMFRECORD (ID=' + CAST(r.ID AS NVARCHAR(20)) + ', TYPE=' + r.RECORDTYPE + ')'
        ELSE 'UNKNOWN'
    END AS PointsTo
FROM CHANGES ch
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = ch.CHANGERECORDID
LEFT JOIN CMFRECORD r ON r.ID = ch.CHANGERECORDID
WHERE ch.CHANGESRECORDID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @OriginalRunID AND TableName = 'CHANGES'
);

-- Check if there are CMFRECORD entries for the individuals
PRINT '';
PRINT '=== CMFRECORD entries for captured individuals ===';
SELECT 
    r.ID AS CMFRecordID,
    r.CASEID,
    r.RECORDTYPE,
    i.INDIVIDUALRECORDID,
    i.FIRSTNAMES,
    i.SURNAME
FROM CMFRECORD r
LEFT JOIN SC_PERSONREGISTRATION_INDIVIDUAL i ON i.INDIVIDUALRECORDID = r.ID
WHERE r.CASEID IN (
    SELECT CAST(PkValue AS BIGINT) FROM dbo.MigrationScenarioRow
    WHERE RunID = @OriginalRunID AND TableName = 'SC_PERSONREGISTRATION_PROPERTIES'
)
ORDER BY r.RECORDTYPE, r.ID;

-- The key insight: CHANGERECORDID points directly to SC_PERSONREGISTRATION_INDIVIDUAL.INDIVIDUALRECORDID
-- NOT to CMFRECORD! The CMFRECORD entries are separate framework records.
PRINT '';
PRINT '=== Conclusion ===';
PRINT 'CHANGES.CHANGERECORDID points to SC_PERSONREGISTRATION_INDIVIDUAL.INDIVIDUALRECORDID';
PRINT 'NOT to CMFRECORD.ID';
PRINT 'The CMFRECORD entries with RECORDTYPE=Changes are separate framework tracking records';
